spring:
  application.name: FishApplication
  data.mongodb.uri: mongodb+srv://vt-service:oarQOT2nBq6xLK7U@developmentcluster.kchsj.mongodb.net/vt-dev?authSource=admin&replicaSet=atlas-47erwk-shard-0&w=majority&readPreference=primary&retryWrites=true&ssl=true
  data.mongodb.database: vt-dev